source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPAppRater_Example' do
  pod 'POPAppRater', :path => '../'
  target 'POPAppRater_Tests' do
  	inherit! :search_paths
  end
end


